/**
 * Always On Mobile - hullo API
 * Welcome to the hullo API.    With this API you can perform operations on your hullo account programmatically that you can call using the hullo console. The operations currently available include:    * Add / Update a member * Get the details of a member * Get the messages sent / received from a member * Send a message to a member  The hullo API is an easy to use RESTful API that can be called by any modern programming language that  supports HTTP calls, and also has out of the box support for several programming languages including:   * Java * Javascript    In order to use the API you will first need to generate an API key using the hullo console application, assigning it the the relevant scopes required for the operations you wish to call. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AttributeType.
* @enum {}
* @readonly
*/
export default class AttributeType {
    
        /**
         * value: "LIST"
         * @const
         */
        "LIST" = "LIST";

    
        /**
         * value: "TEXT"
         * @const
         */
        "TEXT" = "TEXT";

    
        /**
         * value: "FULLNAME"
         * @const
         */
        "FULLNAME" = "FULLNAME";

    
        /**
         * value: "NUMBER"
         * @const
         */
        "NUMBER" = "NUMBER";

    
        /**
         * value: "DATE"
         * @const
         */
        "DATE" = "DATE";

    
        /**
         * value: "BIRTHDAY"
         * @const
         */
        "BIRTHDAY" = "BIRTHDAY";

    
        /**
         * value: "APPOINTMENTDATE"
         * @const
         */
        "APPOINTMENTDATE" = "APPOINTMENTDATE";

    
        /**
         * value: "APPOINTMENTTIME"
         * @const
         */
        "APPOINTMENTTIME" = "APPOINTMENTTIME";

    

    /**
    * Returns a <code>AttributeType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AttributeType} The enum <code>AttributeType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

