/**
 * Always On Mobile - hullo API
 * Welcome to the hullo API.    With this API you can perform operations on your hullo account programmatically that you can call using the hullo console. The operations currently available include:    * Add / Update a member * Get the details of a member * Get the messages sent / received from a member * Send a message to a member  The hullo API is an easy to use RESTful API that can be called by any modern programming language that  supports HTTP calls, and also has out of the box support for several programming languages including:   * Java * Javascript    In order to use the API you will first need to generate an API key using the hullo console application, assigning it the the relevant scopes required for the operations you wish to call. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessageStatus from './MessageStatus';

/**
 * The Message model module.
 * @module model/Message
 * @version 1.0.0
 */
class Message {
    /**
     * Constructs a new <code>Message</code>.
     * A record containing information about a message
     * @alias module:model/Message
     * @param phoneNumber {String} The phone number the message was sent to / received from
     * @param messageText {String} The message text to send / was sent to the member
     */
    constructor(phoneNumber, messageText) { 
        
        Message.initialize(this, phoneNumber, messageText);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phoneNumber, messageText) { 
        obj['phoneNumber'] = phoneNumber;
        obj['messageText'] = messageText;
    }

    /**
     * Constructs a <code>Message</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Message} obj Optional instance to populate.
     * @return {module:model/Message} The populated <code>Message</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Message();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('issueDate')) {
                obj['issueDate'] = ApiClient.convertToType(data['issueDate'], 'Date');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('messageText')) {
                obj['messageText'] = ApiClient.convertToType(data['messageText'], 'String');
            }
            if (data.hasOwnProperty('fullName')) {
                obj['fullName'] = ApiClient.convertToType(data['fullName'], 'String');
            }
            if (data.hasOwnProperty('inbound')) {
                obj['inbound'] = ApiClient.convertToType(data['inbound'], 'Boolean');
            }
            if (data.hasOwnProperty('deliveryStatus')) {
                obj['deliveryStatus'] = MessageStatus.constructFromObject(data['deliveryStatus']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Message</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Message</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Message.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['phoneNumber'] && !(typeof data['phoneNumber'] === 'string' || data['phoneNumber'] instanceof String)) {
            throw new Error("Expected the field `phoneNumber` to be a primitive type in the JSON string but got " + data['phoneNumber']);
        }
        // ensure the json data is a string
        if (data['messageText'] && !(typeof data['messageText'] === 'string' || data['messageText'] instanceof String)) {
            throw new Error("Expected the field `messageText` to be a primitive type in the JSON string but got " + data['messageText']);
        }
        // ensure the json data is a string
        if (data['fullName'] && !(typeof data['fullName'] === 'string' || data['fullName'] instanceof String)) {
            throw new Error("Expected the field `fullName` to be a primitive type in the JSON string but got " + data['fullName']);
        }

        return true;
    }


}

Message.RequiredProperties = ["phoneNumber", "messageText"];

/**
 * The unique ID for the message once submitted
 * @member {String} id
 */
Message.prototype['id'] = undefined;

/**
 * The date the message was will be / was issued. When sending a message this date should be at least 2 minutes in the future
 * @member {Date} issueDate
 */
Message.prototype['issueDate'] = undefined;

/**
 * The phone number the message was sent to / received from
 * @member {String} phoneNumber
 */
Message.prototype['phoneNumber'] = undefined;

/**
 * The message text to send / was sent to the member
 * @member {String} messageText
 */
Message.prototype['messageText'] = undefined;

/**
 * The full name of the member the message was sent to (read only)
 * @member {String} fullName
 */
Message.prototype['fullName'] = undefined;

/**
 * If the message was received from a members phone then this will be marked as true (read only)
 * @member {Boolean} inbound
 */
Message.prototype['inbound'] = undefined;

/**
 * @member {module:model/MessageStatus} deliveryStatus
 */
Message.prototype['deliveryStatus'] = undefined;






export default Message;

