/**
 * Always On Mobile - hullo API
 * Welcome to the hullo API.    With this API you can perform operations on your hullo account programmatically that you can call using the hullo console. The operations currently available include:    * Add / Update a member * Get the details of a member * Get the messages sent / received from a member * Send a message to a member  The hullo API is an easy to use RESTful API that can be called by any modern programming language that  supports HTTP calls, and also has out of the box support for several programming languages including:   * Java * Javascript    In order to use the API you will first need to generate an API key using the hullo console application, assigning it the the relevant scopes required for the operations you wish to call. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GenericError from '../model/GenericError';
import Member from '../model/Member';

/**
* Members service.
* @module api/MembersApi
* @version 1.0.0
*/
export default class MembersApi {

    /**
    * Constructs a new MembersApi. 
    * @alias module:api/MembersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getMember operation.
     * @callback module:api/MembersApi~getMemberCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Member} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets the details for a member
     * Retrieves the details hullo stores about a specific member. The record will contain any attribute data added  using either the hullo API or the hullo application along with the members phone number and full name. 
     * @param {String} phoneNumber The phone number of the subscriber
     * @param {module:api/MembersApi~getMemberCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Member}
     */
    getMember(phoneNumber, callback) {
      let postBody = null;
      // verify the required parameter 'phoneNumber' is set
      if (phoneNumber === undefined || phoneNumber === null) {
        throw new Error("Missing the required parameter 'phoneNumber' when calling getMember");
      }

      let pathParams = {
        'phoneNumber': phoneNumber
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Member;
      return this.apiClient.callApi(
        '/endpoints/members/{phoneNumber}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the optOutMember operation.
     * @callback module:api/MembersApi~optOutMemberCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Opts the member out from the hullo member store
     * Opts out the member from the hullo member store which results in their record being deleted. Any pending  messages will also be deleted for the member and the member will no longer be able to participate in \\ any  campaigns. 
     * @param {String} phoneNumber The phone number of the subscriber
     * @param {module:api/MembersApi~optOutMemberCallback} callback The callback function, accepting three arguments: error, data, response
     */
    optOutMember(phoneNumber, callback) {
      let postBody = null;
      // verify the required parameter 'phoneNumber' is set
      if (phoneNumber === undefined || phoneNumber === null) {
        throw new Error("Missing the required parameter 'phoneNumber' when calling optOutMember");
      }

      let pathParams = {
        'phoneNumber': phoneNumber
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/endpoints/members/{phoneNumber}/optout', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the upsertMember operation.
     * @callback module:api/MembersApi~upsertMemberCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Member} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds or updates a member
     * Add or update the information hullo stores for a specific member. If the member doesn't already exist then    they will be added to the members store and an opt-in message will be sent to the number specified in order   to get confirmation that the number exists and wishes to receive messages. If the member responds with a   confirmation message (\"yes\") then their member record will be updated to opted-in and they will then be able   to receive messages sent to them from any hullo campaign. If the member already exists then their record will  be updated to reflect any new / updated attribute data included in the call. If an attribute is specified but   no value is given or the value is null then that attribute will be deleted from the members record. 
     * @param {module:model/Member} member A JSON object containing member information
     * @param {module:api/MembersApi~upsertMemberCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Member}
     */
    upsertMember(member, callback) {
      let postBody = member;
      // verify the required parameter 'member' is set
      if (member === undefined || member === null) {
        throw new Error("Missing the required parameter 'member' when calling upsertMember");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Member;
      return this.apiClient.callApi(
        '/endpoints/members', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
